name: Benjamin
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5

  flutter_svg: ^2.0.5
  intl: ^0.18.0
  eva_icons_flutter: ^3.1.0
  flutter_staggered_grid_view: ^0.4.0
  percent_indicator: ^4.2.3
  fl_chart: ^0.62.0
  google_fonts: ^4.0.4
  shared_preferences: ^2.1.1
  json_annotation: ^4.8.1
  encrypt: ^5.0.1
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.2
  hexcolor: ^3.0.1
  awesome_dialog: ^2.2.1
  lottie: ^2.4.0
  url_launcher: ^6.1.12
  share_plus: ^7.1.0
  dio: ^5.3.2
  image_picker: ^1.0.2

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.3.1

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#031b03"
  image: "assets/images/logo.png"

  fullscreen: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#031b03"
    theme_color: "#031b03"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/profile/
    - assets/svg/
    - assets/images/raster/.
    - assets/images/vector/.
    - assets/lotties/

  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 900
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 800
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSans-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/IBMPlexSans-Thin.ttf
          weight: 100
